### ISSUE TITLE
OPRS command: Is it possible to run with multiple forward/reverse reads?

### ISSUE THREAD

**Issue by sgsutcliffe** [SushiLab/OPR_Finder#1]
Cool tool! I really like the idea.

I am just wondering if I can include multiple viral sequence runs simultaneously with OPRS command.
Was not clear from wording in the manual. I am guessing 'no' due to fact they are positional arguments?

If not, would it be possible to add in the future?

Thanks for making this tool!

**Comment by hjruscheweyh** [comment]
Hi @sgsutcliffe 

Thank you for interest in the tool. 

It is currently not possible to include sequencing data from multiple runs. This is by design as 1. We do not want users to mix runs from potentially different treatments and 2. the OPRS output files can just be concatenated to get the same result (assuming a similar/same insert size distribution).

Best,
hans

**Comment by sgsutcliffe** [comment]
Thanks! 

I overcame the issue by concatenating the replicates. Seems to have worked :)
